// web/CASVueFrontend/src/command-api-frontend/src/components/CommandList.vue
<script>
export default {
    props: {
        commands: {
            type: Array,
            default: () => []
        },
        activeId: Number
    },
    emit: ['on-command-click'],
    computed: {
        activeCommandClass() {
            return command => command.id === this.activeId ? 'is-active' : ''
        }
    },
    methods: {
        onCommandClick(command){
            this.$emit('on-command-click', command)
        }
    }
    
}
</script>

<template>
    <ul class="list-group command-list mb-3">
        <li v-for="command in commands"
            :key="command.id"
            @click="onCommandClick(command)"
            :class="`${activeCommandClass(command)} list-group-item d-flex justify-content-between lh-condensed command-list-item`">
            <div>
            <h6 class="my-0">{{command.HowTo}}</h6>
            <small class="text-muted">{{command.platform}}</small>
            </div>
            <span class="text-muted">{{command.howTo}}</span>
        </li>
    </ul>
</template>

<style scoped lang="scss">
    .command-list {
        max-height: 300px;
        overflow-y: auto;
        &-item {
            &:hover {
                background-color: #f3f3f3;
            }
            cursor: pointer;
        }

    }
    .is-active {
         background-color: #f3f3f3;   
    }
</style>

// web/CASNgFrontend/src/cas-frontend/src/app/commands/components/command-list/command-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Command } from '../../models/Command'

@Component({
  selector: 'app-command-list',
  templateUrl: './command-list.component.html',
  styleUrls: ['./command-list.component.scss']
})
export class CommandListComponent {
  @Input() commands : Command[];
  @Output() onCommandClicked = new EventEmitter<Command>()
  
  handleCommandClick (command: Command) {
    this.onCommandClicked.next(command)
  }
}

<ul class="list-group mb-3">
  <li 
    *ngFor="let command of commands" 
    (click)="handleCommandClick(command)"
    class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">{{command.commandLine}}</h6>
      <small class="text-muted">{{command.description}}</small>
    </div>
    <span class="text-muted">{{command.platform}}</span>
  </li>
</ul>
