// web/CASVueFrontend/src/command-api-frontend/src/components/CommandSearch.vue
<script>
export default {
    emits: ['on-search']
}
</script>

<template>
  <form class="card p-2">
    <div class="input-group">
      <input
        @keyup="$emit('on-search', $event.target.value)"
        type="text" 
        class="form-control" 
        placeholder="Type to search" />
    </div>
    </form>
</template>

// web/CASNgFrontend/src/cas-frontend/src/app/commands/components/command-search/command-search.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-command-search',
  templateUrl: './command-search.component.html',
  styleUrls: ['./command-search.component.scss']
})
export class CommandSearchComponent {

  @Output() onSearch = new EventEmitter<Event>()

}

<form class="card-p-2">
  <div class="input-group">
    <input 
      (input)="onSearch.emit($event)"
      type="text" 
      class="form-control" 
      placeholder="Command Title"/>
    <div class="input-group-append">
      <button type="submit" class="btn btn-secondary">Search</button>
    </div>
  </div>
</form>
